export enum PathAPI {
    Auth = '/auth',
    Register = '/auth/register',
    Login = '/auth/login',
    Logout = '/auth/logout',
    Review = '/review',
    Search = '/item/search',
    GetReview = '/review/get-reviews',
    GetPopularTags = '/review/get-popular-tags',
    GetLatestReviews = '/review/last-reviews',
    GetPopularReviews = '/review/popular-reviews',
    GetUsers = '/user/get-users',
    GetUser = '/user/get-user',
    Comment = '/item/comment',
    Tags = '/item/tags',
    Rating = '/review/rating',
    Like = '/review/like',
    UploadPhoto = '/user/upload-info',
}
