export enum PathAPI {
    Auth = '/auth',
    Register = '/auth/register',
    Login = '/auth/login',
    Logout = '/auth/logout',
    Review = '/review',
    GetReview = '/review/get-review',
    GetPopularTags = '/review/get-popular-tags',
    GetLatestReviews = '/review/last-reviews',
    GetUsers = '/user/get-users',
    GetUser = '/user/get-user',
    Comment = '/comment',
    Rating = '/review/rating',
    UploadPhoto = '/user/upload-info',
}
